name: Docker Image CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        
    - name: Code quality check
      run: |
        flake8 . --max-line-length=100 --count --statistics
        
    - name: Validate Flask application
      run: |
        pip install flask
        # Проверка существования файла и базовая синтаксическая проверка
        python -c "import py_compile; py_compile.compile('app.py')"
        # Запуск приложения с таймаутом (запускается в фоне и затем убивается)
        timeout 5s python app.py || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
        
    - name: Test Dockerfile validity
      run: |
        docker build -t test-image .
        
    - name: Docker Hub Authentication
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and Push container
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          leahcim04011/muzynchenko2203:latest
          leahcim04011/muzynchenko2203:${{ github.run_number }}
